InfiniteColorEngineRgbw.cpp: add missing cstring include
This fixes a build error found on LibreELEC master:

error: 'memcpy' is not a member of 'std'; did you mean 'wmemcpy'?

Signed-off-by: Matthias Reichl <hias@horus.com>